name: hybrid_graphs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.0=py312h033f2cf_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - brotli-python=1.1.0=py312h1289d80_4
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_0
  - debugpy=1.8.17=py312h8285ef7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - frozenlist=1.7.0=py312h447239a_0
  - greenlet=3.2.4=py312h1289d80_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyha191276_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h7900ff3_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - langchain=1.0.0=pymin310_h332efcf_0
  - langchain-core=1.0.0=pyhd8ed1ab_0
  - langchain-ollama=1.0.0=pyhcf101f3_0
  - langchain-text-splitters=0.3.11=pyhd8ed1ab_0
  - langgraph=1.0.1=pyhd8ed1ab_0
  - langgraph-checkpoint=3.0.0=pyhcf101f3_0
  - langgraph-prebuilt=1.0.1=pyhcf101f3_0
  - langgraph-sdk=0.2.9=pyhcf101f3_0
  - langsmith=0.3.45=pyhd8ed1ab_1
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libcblas=3.9.0=37_h0358290_openblas
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - multidict=6.6.3=py312h178313f_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.3=py312h33ff503_0
  - ollama-python=0.6.0=pyhd8ed1ab_0
  - openssl=3.5.4=h26f9b46_0
  - orjson=3.11.3=py312h868fb18_1
  - ormsgpack=1.11.0=py312hb1f2c67_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h178313f_0
  - psutil=7.1.1=py312h4c3975b_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py312h868fb18_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.0=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py312h0d868a3_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.44=py312h4c3975b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py312h4c3975b_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.20.1=py312h178313f_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py312h4c3975b_3
  - pip:
      - blis==1.3.0
      - catalogue==2.0.10
      - click==8.3.0
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cymem==2.0.11
      - en-core-web-trf==3.8.0
      - filelock==3.20.0
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - langcodes==3.5.0
      - language-data==1.3.0
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.13
      - networkx==3.5
      - nvidia-cublas==13.0.0.19
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile==1.15.0.42
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand==10.4.0.35
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - nvidia-nvtx-cu12==12.8.90
      - pillow==12.0.0
      - preshed==3.0.10
      - rapidfuzz==3.14.1
      - regex==2025.10.22
      - rich==14.2.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentence-transformers==5.1.2
      - shellingham==1.5.4
      - smart-open==7.4.0
      - spacy==3.8.7
      - spacy-alignments==0.9.2
      - spacy-curated-transformers==0.3.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-transformers==1.3.9
      - srsly==2.5.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - thinc==8.3.6
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.9.0+cu130
      - torchvision==0.24.0+cu130
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.5.0
      - typer==0.20.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==2.0.0
prefix: /home/george/anaconda3/envs/hybrid_graphs
